version: '3.8'

services:
  image: mysql:5.7
  container_name: mysql
  volumes:
   - mysql-data
  environment:
   MYSQL_DATABASE= mydb
   MYSQL_ROOT_PASSWORD= admin
  ports: 3307:3306
  networks: 
   - twotier

